// P2.2: Svelte Application Entry
import { mount } from 'svelte';
// Ensure CSS is imported if generated by Vite
import './app.css'; 
import App from './app/App.svelte';

const target = document.getElementById('app');

if (!target) {
    throw new Error('Root element #app not found');
}

const app = mount(App, {
    target: target,
});

export default app;