// P2.2: Svelte Application Entry
// Ensure CSS is imported if generated by Vite
import './app.css';
import App from './app/App.svelte';

// Initialize VS Code API for webview communication

// Acquire VS Code API
const vscode = window.acquireVsCodeApi?.();

const target = document.getElementById('app');

if (!target) {
    throw new Error('Root element #app not found');
}

let app: any;

try {
    // Mount the Svelte application (Svelte 4 uses constructor)
    app = new App({
        target: target,
        props: {
            // Pass any initial props if needed
        }
    });
} catch (error) {
    console.error('Failed to mount Svelte application:', error);

    // Show user-friendly error message
    target.innerHTML = `
        <div style="padding: 20px; text-align: center; color: #ff6b6b;">
            <h2>Application Error</h2>
            <p>Failed to initialize the application. Please try reloading the window.</p>
            <details style="margin-top: 10px; text-align: left;">
                <summary>Error Details</summary>
                <pre style="background: #f5f5f5; padding: 10px; margin: 10px 0; border-radius: 4px; overflow: auto;">${error instanceof Error ? error.message : String(error)}</pre>
            </details>
        </div>
    `;
}

// --- IPC Initialization ---
if (vscode) {
    // 3. IPC Initialization: Send WebviewReadyRequest to host
    // Note: The exact message structure will be defined in protocol.ts (TODO #4)
    // Sending a basic command structure here for now.
    vscode.postMessage({
        command: 'ipc:ready-request', // Placeholder command name
        payload: undefined,
    });
}
// --- End IPC Initialization ---

// Export app instance and cleanup function
export { app };

// Cleanup function for when the webview is disposed
export function cleanup() {
    if (app && typeof app.$destroy === 'function') {
        app.$destroy();
    }
}

// Handle page unload for cleanup
window.addEventListener('unload', cleanup);